// Supported currencies and their default symbols. The active currency is
// stored in ShopSettings; the frontend formats amounts using the symbol.
// This is a curated set of major/regionally-relevant currencies, not the
// full ISO 4217 list.
const CURRENCIES = {
  INR: { symbol: 'Rs.', label: 'Indian Rupee' },
  USD: { symbol: '$', label: 'US Dollar' },
  EUR: { symbol: '€', label: 'Euro' },
  GBP: { symbol: '£', label: 'British Pound' },
  AED: { symbol: 'د.إ', label: 'UAE Dirham' },
  AUD: { symbol: 'A$', label: 'Australian Dollar' },
  CAD: { symbol: 'C$', label: 'Canadian Dollar' },
  SGD: { symbol: 'S$', label: 'Singapore Dollar' },
  HKD: { symbol: 'HK$', label: 'Hong Kong Dollar' },
  JPY: { symbol: '¥', label: 'Japanese Yen' },
  CNY: { symbol: '¥', label: 'Chinese Yuan' },
  CHF: { symbol: 'Fr.', label: 'Swiss Franc' },
  NZD: { symbol: 'NZ$', label: 'New Zealand Dollar' },
  ZAR: { symbol: 'R', label: 'South African Rand' },
  SAR: { symbol: '﷼', label: 'Saudi Riyal' },
  QAR: { symbol: '﷼', label: 'Qatari Riyal' },
  THB: { symbol: '฿', label: 'Thai Baht' },
  MYR: { symbol: 'RM', label: 'Malaysian Ringgit' },
  IDR: { symbol: 'Rp', label: 'Indonesian Rupiah' },
  PHP: { symbol: '₱', label: 'Philippine Peso' },
  BDT: { symbol: '৳', label: 'Bangladeshi Taka' },
  NPR: { symbol: 'Rs.', label: 'Nepalese Rupee' },
  LKR: { symbol: 'Rs.', label: 'Sri Lankan Rupee' },
  PKR: { symbol: 'Rs.', label: 'Pakistani Rupee' },
  KWD: { symbol: 'د.ك', label: 'Kuwaiti Dinar' },
  BHD: { symbol: 'BD', label: 'Bahraini Dinar' },
  OMR: { symbol: 'ر.ع.', label: 'Omani Rial' },
  JOD: { symbol: 'JD', label: 'Jordanian Dinar' },
  EGP: { symbol: 'E£', label: 'Egyptian Pound' },
  ILS: { symbol: '₪', label: 'Israeli Shekel' },
  TRY: { symbol: '₺', label: 'Turkish Lira' },
  KRW: { symbol: '₩', label: 'South Korean Won' },
  TWD: { symbol: 'NT$', label: 'New Taiwan Dollar' },
  VND: { symbol: '₫', label: 'Vietnamese Dong' },
  MMK: { symbol: 'K', label: 'Myanmar Kyat' },
  KHR: { symbol: '៛', label: 'Cambodian Riel' },
  MVR: { symbol: 'Rf', label: 'Maldivian Rufiyaa' },
  BTN: { symbol: 'Nu.', label: 'Bhutanese Ngultrum' },
  SEK: { symbol: 'kr', label: 'Swedish Krona' },
  NOK: { symbol: 'kr', label: 'Norwegian Krone' },
  DKK: { symbol: 'kr', label: 'Danish Krone' },
  PLN: { symbol: 'zł', label: 'Polish Zloty' },
  CZK: { symbol: 'Kč', label: 'Czech Koruna' },
  HUF: { symbol: 'Ft', label: 'Hungarian Forint' },
  RON: { symbol: 'lei', label: 'Romanian Leu' },
  RUB: { symbol: '₽', label: 'Russian Ruble' },
  UAH: { symbol: '₴', label: 'Ukrainian Hryvnia' },
  MXN: { symbol: 'Mex$', label: 'Mexican Peso' },
  BRL: { symbol: 'R$', label: 'Brazilian Real' },
  ARS: { symbol: 'AR$', label: 'Argentine Peso' },
  CLP: { symbol: 'CL$', label: 'Chilean Peso' },
  COP: { symbol: 'COL$', label: 'Colombian Peso' },
  PEN: { symbol: 'S/', label: 'Peruvian Sol' },
  NGN: { symbol: '₦', label: 'Nigerian Naira' },
  KES: { symbol: 'KSh', label: 'Kenyan Shilling' },
  GHS: { symbol: 'GH₵', label: 'Ghanaian Cedi' },
  MAD: { symbol: 'MAD', label: 'Moroccan Dirham' },
};

function symbolFor(code, fallback) {
  return CURRENCIES[code]?.symbol || fallback || code;
}

module.exports = { CURRENCIES, symbolFor };
